### ISSUE TITLE
Code is not good

### ISSUE THREAD

**Issue by PEMapModder** [PurePlugins/PharUtils#1]
I cannot find any good code in this repo.

**Comment by 64FF00** [comment]
@PEMapModder That's a good thing :+1:

**Comment by 64FF00** [comment]
@PEMapModder Our first pointless commit! https://github.com/PurePlugins/PharUtils/commit/f289499e89e76edeb8ebea647ac92e6b8872f1a7

**Comment by PEMapModder** [comment]
:D

**Comment by 64FF00** [comment]
:+1:
